### ISSUE TITLE
Update dbSNP 138 in the workflow

### ISSUE THREAD

**Issue by cariaso** [seqeralabs/gatk4-germline-snps-indels#32]
dbSNP 138 is from April of 2013. It has only 4% of the current 1B human rs#s in release 155. Why is this part of your example? Is this tool capable of working with current releases?

**Comment by abhi18av** [comment]
Hi @cariaso , 

Thanks for giving this workflow a look and identifying this.

However, this workflow was designed to (i) demonstrate patterns and  (ii) for benchmarking purposes. We might update the `dbSNP` and other aspects to latest versions in future, however that is not a priority as of now.

That being said, we'd be happy to review and merge any pull requests :)

**Comment by abhi18av** [comment]
Closing as stale issue. Please feel free to re-open if still relevant.
