### ISSUE TITLE
sequence_grouping.txt format

### ISSUE THREAD

**Issue by Griffan** [seqeralabs/gatk4-germline-snps-indels#37]
Hi, Developers

Thanks for developing this wonderful one-stop ngs pipeline! 
I'm trying to use this pipeline, but I have a question regarding the format of this config file: sequence_grouping.txt (as well as sequence_grouping_unmapped.txt)

https://github.com/seqeralabs/gatk4-germline-snps-indels/blob/41c8d4b7c62b8f26be8510f8aabe1baaf51dd8e4/nextflow_schema.json#L96

Since I don't have access to the s3 bucket, is it possible to give us an example of what it's like and what it's used for? Thanks!

**Comment by abhi18av** [comment]
Hi @Griffan , 

> Thanks for developing this wonderful one-stop ngs pipeline!

Thank you:) However, I must highlight that this workflow was designed to (i) demonstrate patterns and (ii) for benchmarking purposes. 

As therefore, it uses older versions of the tools, perhaps you might be interested in nf-core pipelines (sarek) for this purpose.

> Since I don't have access to the s3 bucket, is it possible to give us an example of what it's like and what it's used for?


Sure, here's the file which is also bundled as a resource in this repo https://github.com/seqeralabs/gatk4-germline-snps-indels/blob/master/resources/original_public_sources/sequence_grouping.txt
